"use client";

import { useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BadgeCheck, Bell, BriefcaseBusiness, Check, ChevronRight, Clock3, FileCheck2, FileText, Heart, Home, Languages, MapPin, ShieldCheck, Sparkles, UploadCloud, UserRound, ClipboardList, GraduationCap, Stethoscope, Globe2, PlaneTakeoff, SlidersHorizontal, HelpCircle, Settings, MessageCircleQuestion, CalendarDays } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

type Language = "en" | "de" | "ar";
type View = "home" | "jobs" | "documents" | "profile" | "job" | "intake" | "jobPreferences" | "settings" | "help";

const copy = {
  en: { greeting:"Good morning, Amira",subtitle:"Your path to working in Germany",completion:"Profile strength",completeHint:"Complete your profile to get matched with suitable employers.",continue:"Continue profile",applications:"Applications",saved:"Saved jobs",matches:"New matches",recommended:"Recommended for you",seeAll:"See all",home:"Home",jobs:"Jobs",documents:"Documents",profile:"Profile",verified:"Verified employer",anonymous:"Employer details shared after matching",viewJob:"View position",apply:"Express interest",interestSent:"Interest sent",jobTitle:"Registered nurse",jobTitle2:"Nursing trainee",jobTitle3:"Geriatric care specialist",city1:"Cologne area",city2:"Düsseldorf area",city3:"Bonn area",fulltime:"Full-time",salary:"€3,400–€4,100 / month",salary2:"Training allowance",language:"German B2 desired",lang2:"German B1 sufficient",about:"About this position",aboutText:"A modern care provider in North Rhine-Westphalia is looking for international nursing professionals. MediBridge supports the full journey from first contact to arrival in Germany.",support:"MediBridge support",supportText:"Document review, recognition guidance, interview preparation and relocation support.",docsTitle:"Your documents",docsSubtitle:"Upload clear, complete files. We review every document before sharing it with an employer.",upload:"Upload document",uploadHint:"PDF, JPG or PNG · max. 10 MB",uploaded:"Uploaded",inReview:"In review",missing:"Still needed",diploma:"Nursing diploma",languageCert:"Language certificate",passport:"Passport / ID",workRef:"Employment reference",verifiedCandidate:"Candidate verification",verificationText:"Your identity and qualifications are currently being reviewed.",profileTitle:"Candidate profile",personal:"Personal details",name:"Full name",country:"Country of residence",role:"Profession",experience:"Work experience",level:"German level",edit:"Edit profile",save:"Save changes",cvTitle:"Create your German CV",cvText:"A guided questionnaire will turn your information into a professional CV.",comingSoon:"Coming in the next step",privacy:"Your data stays private",privacyText:"Employers only receive your details after you approve a match.",welcome:"Find your career in Germany",welcomeText:"Create your candidate profile and let MediBridge connect you with verified healthcare employers.",start:"Create my profile",haveAccount:"I already have an account" },
  de: { greeting:"Guten Morgen, Amira",subtitle:"Dein Weg in den deutschen Arbeitsmarkt",completion:"Profilstärke",completeHint:"Vervollständige dein Profil, damit wir passende Arbeitgeber finden.",continue:"Profil fortsetzen",applications:"Bewerbungen",saved:"Gemerkt",matches:"Neue Treffer",recommended:"Für dich empfohlen",seeAll:"Alle ansehen",home:"Start",jobs:"Jobs",documents:"Dokumente",profile:"Profil",verified:"Geprüfter Arbeitgeber",anonymous:"Arbeitgeberdaten nach erfolgreichem Matching",viewJob:"Stelle ansehen",apply:"Interesse zeigen",interestSent:"Interesse gesendet",jobTitle:"Pflegefachkraft",jobTitle2:"Ausbildung Pflegefachkraft",jobTitle3:"Altenpflegefachkraft",city1:"Raum Köln",city2:"Raum Düsseldorf",city3:"Raum Bonn",fulltime:"Vollzeit",salary:"3.400–4.100 € / Monat",salary2:"Ausbildungsvergütung",language:"Deutsch B2 erwünscht",lang2:"Deutsch B1 ausreichend",about:"Über diese Stelle",aboutText:"Ein moderner Pflegeanbieter in Nordrhein-Westfalen sucht internationale Pflegefachkräfte. MediBridge begleitet den gesamten Weg vom Erstkontakt bis zur Ankunft in Deutschland.",support:"MediBridge-Begleitung",supportText:"Dokumentenprüfung, Anerkennungsberatung, Interviewvorbereitung und Unterstützung beim Umzug.",docsTitle:"Deine Dokumente",docsSubtitle:"Lade gut lesbare und vollständige Unterlagen hoch. Wir prüfen jedes Dokument vor der Weitergabe.",upload:"Dokument hochladen",uploadHint:"PDF, JPG oder PNG · max. 10 MB",uploaded:"Hochgeladen",inReview:"In Prüfung",missing:"Noch erforderlich",diploma:"Pflegediplom",languageCert:"Sprachzertifikat",passport:"Reisepass / Ausweis",workRef:"Arbeitszeugnis",verifiedCandidate:"Kandidatenprüfung",verificationText:"Deine Identität und Qualifikationen werden aktuell geprüft.",profileTitle:"Kandidatenprofil",personal:"Persönliche Daten",name:"Vollständiger Name",country:"Wohnsitzland",role:"Beruf",experience:"Berufserfahrung",level:"Deutschniveau",edit:"Profil bearbeiten",save:"Änderungen speichern",cvTitle:"Deutschen Lebenslauf erstellen",cvText:"Ein geführter Fragebogen erstellt aus deinen Angaben einen professionellen Lebenslauf.",comingSoon:"Im nächsten Schritt verfügbar",privacy:"Deine Daten bleiben geschützt",privacyText:"Arbeitgeber erhalten deine Daten erst, nachdem du einem Match zugestimmt hast.",welcome:"Deine Karriere in Deutschland",welcomeText:"Erstelle dein Kandidatenprofil und lass dich von MediBridge mit geprüften Arbeitgebern im Gesundheitswesen verbinden.",start:"Profil erstellen",haveAccount:"Ich habe bereits ein Konto" },
  ar: { greeting:"صباح الخير، أميرة",subtitle:"طريقك للعمل في ألمانيا",completion:"اكتمال الملف",completeHint:"أكملي ملفك لنجد لك أصحاب العمل المناسبين.",continue:"متابعة الملف",applications:"الطلبات",saved:"الوظائف المحفوظة",matches:"فرص جديدة",recommended:"مقترحة لك",seeAll:"عرض الكل",home:"الرئيسية",jobs:"الوظائف",documents:"الوثائق",profile:"الملف",verified:"جهة عمل موثقة",anonymous:"تظهر بيانات جهة العمل بعد المطابقة",viewJob:"عرض الوظيفة",apply:"إبداء الاهتمام",interestSent:"تم إرسال الاهتمام",jobTitle:"ممرض/ة مؤهل/ة",jobTitle2:"تدريب مهني في التمريض",jobTitle3:"أخصائي/ة رعاية المسنين",city1:"منطقة كولونيا",city2:"منطقة دوسلدورف",city3:"منطقة بون",fulltime:"دوام كامل",salary:"3,400–4,100 € شهرياً",salary2:"راتب التدريب",language:"يفضل مستوى B2 بالألمانية",lang2:"مستوى B1 بالألمانية كافٍ",about:"عن هذه الوظيفة",aboutText:"تبحث مؤسسة رعاية حديثة في شمال الراين-وستفاليا عن كوادر تمريض دولية. ترافقك MediBridge من أول تواصل حتى الوصول إلى ألمانيا.",support:"دعم MediBridge",supportText:"مراجعة الوثائق، إرشاد المعادلة، التحضير للمقابلة ودعم الانتقال.",docsTitle:"وثائقك",docsSubtitle:"ارفعي ملفات واضحة وكاملة. نراجع كل وثيقة قبل مشاركتها مع جهة العمل.",upload:"رفع وثيقة",uploadHint:"PDF أو JPG أو PNG · حتى 10 MB",uploaded:"تم الرفع",inReview:"قيد المراجعة",missing:"مطلوب",diploma:"شهادة التمريض",languageCert:"شهادة اللغة",passport:"جواز السفر / الهوية",workRef:"شهادة خبرة",verifiedCandidate:"توثيق المرشح",verificationText:"تجري حالياً مراجعة هويتك ومؤهلاتك.",profileTitle:"ملف المرشح",personal:"البيانات الشخصية",name:"الاسم الكامل",country:"بلد الإقامة",role:"المهنة",experience:"سنوات الخبرة",level:"مستوى الألمانية",edit:"تعديل الملف",save:"حفظ التغييرات",cvTitle:"إنشاء سيرة ذاتية ألمانية",cvText:"سيحوّل استبيان موجه بياناتك إلى سيرة ذاتية احترافية.",comingSoon:"متاح في الخطوة القادمة",privacy:"بياناتك تبقى خاصة",privacyText:"لا يحصل أصحاب العمل على بياناتك إلا بعد موافقتك على المطابقة.",welcome:"ابدئي مسيرتك المهنية في ألمانيا",welcomeText:"أنشئي ملفك ودعي MediBridge تربطك بجهات عمل موثقة في الرعاية الصحية.",start:"إنشاء ملفي",haveAccount:"لدي حساب بالفعل" },
} as const;

const menuCopy = {
  en:{candidate:"Candidate",profile:"Profile",jobPreferences:"Job preferences",settings:"Settings",help:"Help",preferencesTitle:"Your job preferences",preferencesText:"Tell us what your ideal opportunity in Germany looks like.",desiredRole:"Desired role",preferredRegion:"Preferred region",startDate:"Possible start",workplace:"Preferred workplace",save:"Save preferences",settingsTitle:"Settings",settingsText:"Manage the language and basic app preferences.",helpTitle:"Help and support",helpText:"Find answers or contact MediBridge directly.",faq:"Frequently asked questions",contact:"Contact MediBridge",privacy:"Privacy and data"},
  de:{candidate:"Kandidatin",profile:"Profil",jobPreferences:"Job-Wünsche",settings:"Einstellungen",help:"Hilfe",preferencesTitle:"Deine Job-Wünsche",preferencesText:"Sag uns, wie deine ideale Stelle in Deutschland aussehen soll.",desiredRole:"Gewünschte Tätigkeit",preferredRegion:"Bevorzugte Region",startDate:"Möglicher Start",workplace:"Bevorzugter Arbeitgeber",save:"Job-Wünsche speichern",settingsTitle:"Einstellungen",settingsText:"Verwalte die Sprache und grundlegende App-Einstellungen.",helpTitle:"Hilfe und Support",helpText:"Finde Antworten oder kontaktiere MediBridge direkt.",faq:"Häufige Fragen",contact:"MediBridge kontaktieren",privacy:"Datenschutz und Daten"},
  ar:{candidate:"مرشحة",profile:"الملف الشخصي",jobPreferences:"تفضيلات العمل",settings:"الإعدادات",help:"المساعدة",preferencesTitle:"تفضيلات العمل",preferencesText:"أخبرينا كيف تبدو فرصتك المثالية في ألمانيا.",desiredRole:"الوظيفة المطلوبة",preferredRegion:"المنطقة المفضلة",startDate:"موعد البدء الممكن",workplace:"مكان العمل المفضل",save:"حفظ التفضيلات",settingsTitle:"الإعدادات",settingsText:"إدارة اللغة وإعدادات التطبيق الأساسية.",helpTitle:"المساعدة والدعم",helpText:"اعثري على إجابات أو تواصلي مع MediBridge.",faq:"الأسئلة الشائعة",contact:"التواصل مع MediBridge",privacy:"الخصوصية والبيانات"}
} as const;

const intakeCopy = {
  en: {
    title:"Candidate intake", intro:"Tell us about your background and plans. You can change your answers later.", step:"Step", of:"of", back:"Back", next:"Continue", finish:"Complete intake", saved:"Your intake is complete", savedText:"Thank you. We will review your information before proposing suitable opportunities.", home:"Go to dashboard",
    sections:[
      { title:"Personal and contact details", hint:"How can MediBridge reach you?", questions:[{id:"fullName",label:"Full legal name",type:"text",placeholder:"As shown in your passport"},{id:"birthDate",label:"Date of birth",type:"date"},{id:"nationality",label:"Nationality",type:"text",placeholder:"e.g. Moroccan"},{id:"residence",label:"Current country and city",type:"text",placeholder:"e.g. Rabat, Morocco"},{id:"phone",label:"WhatsApp / phone number",type:"tel",placeholder:"Include country code"},{id:"email",label:"Email address",type:"email",placeholder:"name@example.com"}]},
      { title:"Professional goal", hint:"What kind of opportunity are you looking for?", questions:[{id:"targetRole",label:"Desired position",type:"choice",options:["Registered nurse","Nursing trainee","Nursing assistant","Other healthcare role"]},{id:"start",label:"When could you start?",type:"choice",options:["Immediately","Within 3 months","Within 6 months","Later"]},{id:"facility",label:"Preferred workplace",type:"choice",options:["Hospital","Care home","Outpatient care","Open to all"]}]},
      { title:"Education and recognition", hint:"Your qualifications determine the recognition path in Germany.", questions:[{id:"qualification",label:"Highest healthcare qualification",type:"text",placeholder:"Diploma or degree"},{id:"school",label:"School / university and country",type:"text",placeholder:"Institution name"},{id:"graduation",label:"Graduation year",type:"text",placeholder:"YYYY"},{id:"recognition",label:"Recognition status in Germany",type:"choice",options:["Not started","Documents prepared","Application submitted","Partially recognised","Fully recognised"]}]},
      { title:"Professional experience", hint:"Give us a realistic picture of your practical background.", questions:[{id:"years",label:"Years of professional experience",type:"choice",options:["No experience yet","Under 1 year","1–3 years","4–6 years","More than 6 years"]},{id:"areas",label:"Main clinical areas",type:"textarea",placeholder:"e.g. internal medicine, surgery, elderly care"},{id:"current",label:"Current employment status",type:"choice",options:["Employed","In training","Seeking work","Other"]}]},
      { title:"Language skills", hint:"Language level is central to training, recognition and visa planning.", questions:[{id:"german",label:"Current German level",type:"choice",options:["No German yet","A1","A2","B1","B2 or higher"]},{id:"certificate",label:"Do you have a German certificate?",type:"choice",options:["Yes","Exam booked","Not yet"]},{id:"otherLanguages",label:"Other languages",type:"text",placeholder:"e.g. Arabic, English, French"}]},
      { title:"Mobility and readiness", hint:"This helps us estimate the next practical steps.", questions:[{id:"passport",label:"Do you have a valid passport?",type:"choice",options:["Yes","Applied for","No"]},{id:"visa",label:"Visa / residence status for Germany",type:"choice",options:["Not started","Visa process started","Visa available","Already in Germany"]},{id:"relocation",label:"Are you ready to relocate to Germany?",type:"choice",options:["Yes","Yes, with family","Need more information","Not yet"]},{id:"region",label:"Preferred German region",type:"text",placeholder:"e.g. North Rhine-Westphalia or flexible"},{id:"licence",label:"Driving licence",type:"choice",options:["Yes","No","In progress"]}]},
    ]
  },
  de: {
    title:"Kandidatenaufnahme",intro:"Erzähl uns etwas über deinen Hintergrund und deine Pläne. Du kannst die Angaben später ändern.",step:"Schritt",of:"von",back:"Zurück",next:"Weiter",finish:"Aufnahme abschließen",saved:"Deine Aufnahme ist vollständig",savedText:"Danke. Wir prüfen deine Angaben, bevor wir dir passende Möglichkeiten vorschlagen.",home:"Zum Dashboard",
    sections:[
      {title:"Persönliche Daten und Kontakt",hint:"Wie kann MediBridge dich erreichen?",questions:[{id:"fullName",label:"Vollständiger Name laut Pass",type:"text",placeholder:"Wie im Reisepass"},{id:"birthDate",label:"Geburtsdatum",type:"date"},{id:"nationality",label:"Staatsangehörigkeit",type:"text",placeholder:"z. B. marokkanisch"},{id:"residence",label:"Aktueller Wohnort",type:"text",placeholder:"z. B. Rabat, Marokko"},{id:"phone",label:"WhatsApp / Telefonnummer",type:"tel",placeholder:"Mit Ländervorwahl"},{id:"email",label:"E-Mail-Adresse",type:"email",placeholder:"name@beispiel.de"}]},
      {title:"Berufliches Ziel",hint:"Welche Möglichkeit suchst du?",questions:[{id:"targetRole",label:"Gewünschte Position",type:"choice",options:["Pflegefachkraft","Ausbildung Pflegefachkraft","Pflegehilfskraft","Andere Gesundheitsberufe"]},{id:"start",label:"Wann könntest du starten?",type:"choice",options:["Sofort","Innerhalb von 3 Monaten","Innerhalb von 6 Monaten","Später"]},{id:"facility",label:"Bevorzugter Arbeitgeber",type:"choice",options:["Krankenhaus","Pflegeheim","Ambulante Pflege","Für alles offen"]}]},
      {title:"Ausbildung und Anerkennung",hint:"Dein Abschluss bestimmt den Anerkennungsweg in Deutschland.",questions:[{id:"qualification",label:"Höchster Abschluss im Gesundheitswesen",type:"text",placeholder:"Diplom oder Abschluss"},{id:"school",label:"Schule / Hochschule und Land",type:"text",placeholder:"Name der Einrichtung"},{id:"graduation",label:"Abschlussjahr",type:"text",placeholder:"JJJJ"},{id:"recognition",label:"Stand der Anerkennung in Deutschland",type:"choice",options:["Noch nicht begonnen","Dokumente vorbereitet","Antrag gestellt","Teilweise anerkannt","Voll anerkannt"]}]},
      {title:"Berufserfahrung",hint:"Beschreibe deinen praktischen Hintergrund realistisch.",questions:[{id:"years",label:"Jahre Berufserfahrung",type:"choice",options:["Noch keine Erfahrung","Unter 1 Jahr","1–3 Jahre","4–6 Jahre","Mehr als 6 Jahre"]},{id:"areas",label:"Wichtigste Einsatzbereiche",type:"textarea",placeholder:"z. B. Innere Medizin, Chirurgie, Altenpflege"},{id:"current",label:"Aktueller Beschäftigungsstatus",type:"choice",options:["Beschäftigt","In Ausbildung","Arbeitssuchend","Andere Situation"]}]},
      {title:"Sprachkenntnisse",hint:"Das Sprachniveau ist zentral für Ausbildung, Anerkennung und Visum.",questions:[{id:"german",label:"Aktuelles Deutschniveau",type:"choice",options:["Noch keine Kenntnisse","A1","A2","B1","B2 oder höher"]},{id:"certificate",label:"Deutsches Sprachzertifikat vorhanden?",type:"choice",options:["Ja","Prüfung gebucht","Noch nicht"]},{id:"otherLanguages",label:"Weitere Sprachen",type:"text",placeholder:"z. B. Arabisch, Englisch, Französisch"}]},
      {title:"Mobilität und Bereitschaft",hint:"Damit können wir die nächsten praktischen Schritte einschätzen.",questions:[{id:"passport",label:"Gültiger Reisepass vorhanden?",type:"choice",options:["Ja","Beantragt","Nein"]},{id:"visa",label:"Visum- / Aufenthaltsstatus für Deutschland",type:"choice",options:["Noch nicht begonnen","Visumprozess läuft","Visum vorhanden","Bereits in Deutschland"]},{id:"relocation",label:"Bereit für einen Umzug nach Deutschland?",type:"choice",options:["Ja","Ja, mit Familie","Benötige mehr Informationen","Noch nicht"]},{id:"region",label:"Bevorzugte Region in Deutschland",type:"text",placeholder:"z. B. Nordrhein-Westfalen oder flexibel"},{id:"licence",label:"Führerschein",type:"choice",options:["Ja","Nein","In Arbeit"]}]},
    ]
  },
  ar: {
    title:"استمارة تسجيل المرشح",intro:"أخبرنا عن خبرتك وخططك. يمكنك تعديل إجاباتك لاحقاً.",step:"الخطوة",of:"من",back:"رجوع",next:"متابعة",finish:"إكمال التسجيل",saved:"اكتمل تسجيلك",savedText:"شكراً لك. سنراجع بياناتك قبل اقتراح الفرص المناسبة.",home:"الذهاب إلى الرئيسية",
    sections:[
      {title:"البيانات الشخصية والتواصل",hint:"كيف يمكن لـ MediBridge التواصل معك؟",questions:[{id:"fullName",label:"الاسم الكامل كما في جواز السفر",type:"text",placeholder:"الاسم القانوني"},{id:"birthDate",label:"تاريخ الميلاد",type:"date"},{id:"nationality",label:"الجنسية",type:"text",placeholder:"مثلاً: مغربية"},{id:"residence",label:"بلد ومدينة الإقامة الحالية",type:"text",placeholder:"مثلاً: الرباط، المغرب"},{id:"phone",label:"رقم واتساب / الهاتف",type:"tel",placeholder:"مع رمز البلد"},{id:"email",label:"البريد الإلكتروني",type:"email",placeholder:"name@example.com"}]},
      {title:"الهدف المهني",hint:"ما نوع الفرصة التي تبحث عنها؟",questions:[{id:"targetRole",label:"الوظيفة المطلوبة",type:"choice",options:["ممرض/ة مؤهل/ة","تدريب مهني في التمريض","مساعد/ة تمريض","مهنة صحية أخرى"]},{id:"start",label:"متى يمكنك البدء؟",type:"choice",options:["فوراً","خلال 3 أشهر","خلال 6 أشهر","لاحقاً"]},{id:"facility",label:"مكان العمل المفضل",type:"choice",options:["مستشفى","دار رعاية","رعاية منزلية","منفتح/ة على الجميع"]}]},
      {title:"التعليم والمعادلة",hint:"يحدد مؤهلك مسار المعادلة في ألمانيا.",questions:[{id:"qualification",label:"أعلى مؤهل صحي",type:"text",placeholder:"دبلوم أو شهادة"},{id:"school",label:"المعهد / الجامعة والبلد",type:"text",placeholder:"اسم المؤسسة"},{id:"graduation",label:"سنة التخرج",type:"text",placeholder:"السنة"},{id:"recognition",label:"وضع المعادلة في ألمانيا",type:"choice",options:["لم تبدأ","الوثائق جاهزة","تم تقديم الطلب","معادلة جزئية","معادلة كاملة"]}]},
      {title:"الخبرة المهنية",hint:"قدم صورة واقعية عن خبرتك العملية.",questions:[{id:"years",label:"سنوات الخبرة",type:"choice",options:["دون خبرة","أقل من سنة","1–3 سنوات","4–6 سنوات","أكثر من 6 سنوات"]},{id:"areas",label:"مجالات العمل الأساسية",type:"textarea",placeholder:"مثلاً: الطب الباطني، الجراحة، رعاية المسنين"},{id:"current",label:"الوضع المهني الحالي",type:"choice",options:["أعمل حالياً","في التكوين","أبحث عن عمل","وضع آخر"]}]},
      {title:"المهارات اللغوية",hint:"مستوى اللغة مهم للتكوين والمعادلة والتأشيرة.",questions:[{id:"german",label:"مستوى الألمانية الحالي",type:"choice",options:["لا أتحدث الألمانية","A1","A2","B1","B2 أو أعلى"]},{id:"certificate",label:"هل لديك شهادة ألمانية؟",type:"choice",options:["نعم","الامتحان محجوز","ليس بعد"]},{id:"otherLanguages",label:"لغات أخرى",type:"text",placeholder:"مثلاً: العربية، الإنجليزية، الفرنسية"}]},
      {title:"الاستعداد للانتقال",hint:"يساعدنا هذا على تحديد الخطوات العملية التالية.",questions:[{id:"passport",label:"هل لديك جواز سفر ساري؟",type:"choice",options:["نعم","تم تقديم الطلب","لا"]},{id:"visa",label:"وضع التأشيرة / الإقامة لألمانيا",type:"choice",options:["لم يبدأ","الإجراءات جارية","التأشيرة متوفرة","موجود/ة في ألمانيا"]},{id:"relocation",label:"هل أنت مستعد/ة للانتقال إلى ألمانيا؟",type:"choice",options:["نعم","نعم، مع العائلة","أحتاج معلومات أكثر","ليس بعد"]},{id:"region",label:"المنطقة المفضلة في ألمانيا",type:"text",placeholder:"مثلاً: شمال الراين أو أي منطقة"},{id:"licence",label:"رخصة القيادة",type:"choice",options:["نعم","لا","قيد الإنجاز"]}]},
    ]
  }
} as const;

const jobs = [
  { title:"jobTitle",city:"city1",salary:"salary",language:"language",accent:"teal" },
  { title:"jobTitle2",city:"city2",salary:"salary2",language:"lang2",accent:"coral" },
  { title:"jobTitle3",city:"city3",salary:"salary",language:"language",accent:"green" },
] as const;

const processCopy = {
  en:{documents:"Supporting documents",documentsHint:"Upload the documents that help us verify your profile. Passport and qualification are required.",passport:"Passport / identity document",qualification:"Professional qualification",language:"Language certificate",reference:"Employment reference",required:"Required",optional:"Optional",uploaded:"Uploaded",choose:"Choose file",review:"Review and submit",reviewHint:"Check your details before sending them to MediBridge.",details:"Your information",files:"Your documents",edit:"Edit",consent:"I confirm that my information is correct and consent to MediBridge processing it for recruitment and recognition support.",submit:"Submit candidate intake",submitted:"Application submitted",submittedText:"Your candidate intake is now with the MediBridge team for a personal review.",status:"Under review",referenceNo:"Reference",response:"We normally contact you within 2–3 working days.",nextSteps:"What happens next",next1:"MediBridge checks your profile and documents",next2:"We contact you if anything is missing",next3:"After verification, suitable anonymised jobs are proposed",dashboard:"Go to dashboard",viewStatus:"View intake status"},
  de:{documents:"Nachweise und Dokumente",documentsHint:"Lade Unterlagen hoch, mit denen wir dein Profil prüfen können. Pass und Berufsabschluss sind erforderlich.",passport:"Reisepass / Identitätsnachweis",qualification:"Berufsabschluss / Pflegediplom",language:"Sprachzertifikat",reference:"Arbeitszeugnis",required:"Erforderlich",optional:"Optional",uploaded:"Hochgeladen",choose:"Datei auswählen",review:"Prüfen und absenden",reviewHint:"Prüfe alle Angaben, bevor du sie verbindlich an MediBridge sendest.",details:"Deine Angaben",files:"Deine Dokumente",edit:"Bearbeiten",consent:"Ich bestätige, dass meine Angaben richtig sind, und willige in die Verarbeitung durch MediBridge für Vermittlung und Anerkennungsbegleitung ein.",submit:"Kandidatenaufnahme absenden",submitted:"Aufnahme erfolgreich übermittelt",submittedText:"Deine Kandidatenaufnahme liegt jetzt dem MediBridge-Team zur persönlichen Prüfung vor.",status:"In Prüfung",referenceNo:"Vorgangsnummer",response:"Wir melden uns in der Regel innerhalb von 2–3 Werktagen.",nextSteps:"So geht es weiter",next1:"MediBridge prüft Profil und Dokumente",next2:"Bei fehlenden Angaben kontaktieren wir dich",next3:"Nach der Verifizierung erhältst du passende anonymisierte Stellen",dashboard:"Zum Dashboard",viewStatus:"Status der Aufnahme"},
  ar:{documents:"المستندات الداعمة",documentsHint:"ارفع المستندات اللازمة للتحقق من ملفك. جواز السفر والمؤهل المهني مطلوبان.",passport:"جواز السفر / إثبات الهوية",qualification:"المؤهل المهني / دبلوم التمريض",language:"شهادة اللغة",reference:"شهادة الخبرة",required:"مطلوب",optional:"اختياري",uploaded:"تم الرفع",choose:"اختيار ملف",review:"المراجعة والإرسال",reviewHint:"راجع جميع بياناتك قبل إرسالها إلى MediBridge.",details:"بياناتك",files:"مستنداتك",edit:"تعديل",consent:"أؤكد صحة بياناتي وأوافق على معالجتها من قبل MediBridge لأغراض التوظيف ودعم معادلة المؤهلات.",submit:"إرسال تسجيل المرشح",submitted:"تم إرسال التسجيل بنجاح",submittedText:"ملف تسجيلك الآن لدى فريق MediBridge للمراجعة الشخصية.",status:"قيد المراجعة",referenceNo:"رقم الملف",response:"نتواصل معك عادة خلال يومي عمل إلى ثلاثة أيام.",nextSteps:"الخطوات التالية",next1:"يراجع MediBridge ملفك ومستنداتك",next2:"نتواصل معك إذا كانت هناك معلومات ناقصة",next3:"بعد التحقق نقترح عليك وظائف مناسبة ومجهولة الجهة",dashboard:"الذهاب إلى الرئيسية",viewStatus:"عرض حالة التسجيل"}
} as const;

export default function HomePage() {
  const [lang,setLang]=useState<Language>("en"); const [view,setView]=useState<View>("home"); const [onboarded,setOnboarded]=useState(false); const [editing,setEditing]=useState(false); const [savedJobs,setSavedJobs]=useState<number[]>([1]); const [selectedJob,setSelectedJob]=useState(0); const [interested,setInterested]=useState(false); const [files,setFiles]=useState<string[]>([]); const [intakeStep,setIntakeStep]=useState(0); const [intakeAnswers,setIntakeAnswers]=useState<Record<string,string>>({}); const [intakeDocuments,setIntakeDocuments]=useState<Record<string,string>>({}); const [intakeConsent,setIntakeConsent]=useState(false); const [intakeSubmitted,setIntakeSubmitted]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const t=copy[lang]; const rtl=lang==="ar";
  const openJob=(i:number)=>{setSelectedJob(i);setInterested(false);setView("job")};
  if(!onboarded) return <main className="welcome-shell" dir={rtl?"rtl":"ltr"}><section className="welcome-card"><Brand/><div className="welcome-visual" aria-hidden="true"><div className="passport-card"><span>MB</span><BadgeCheck/></div><div className="journey-line"><span>✦</span></div><div className="germany-card"><span>DE</span><Check/></div></div><div><p className="eyebrow">MEDIBRIDGE CAREERS</p><h1>{t.welcome}</h1><p className="lead">{t.welcomeText}</p></div><div className="welcome-actions"><button className="primary-button" onClick={()=>{setOnboarded(true);setView("intake")}}>{t.start}<ArrowRight size={18}/></button><button className="text-button" onClick={()=>setOnboarded(true)}>{t.haveAccount}</button></div><p className="privacy-line"><ShieldCheck size={16}/>{t.privacy}</p></section></main>;
  const focused=view==="job"||view==="intake"||view==="jobPreferences"||view==="settings"||view==="help";
  return <main className="app-shell" dir={rtl?"rtl":"ltr"}><div className="app-frame"><header className={`topbar ${focused?"focused":"main-header"}`}>{focused?<><button className="icon-button header-back" onClick={()=>view==="job"?setView("jobs"):setView("profile")} aria-label="Back"><ArrowLeft size={21}/></button><div className="header-brand"><Brand compact/></div><span className="header-spacer"/></>:<><div className="header-profile"><ProfileMenu lang={lang} setView={setView} compact/></div><div className="header-brand"><Brand compact/></div><button className="icon-button header-bell" aria-label="Notifications"><Bell size={20}/><i/></button></>}</header><div className="page-content">{view==="home"&&<Dashboard t={t} lang={lang} submitted={intakeSubmitted} openJob={openJob} setView={setView}/>} {view==="jobs"&&<JobsList t={t} savedJobs={savedJobs} setSavedJobs={setSavedJobs} openJob={openJob}/>} {view==="documents"&&<Documents t={t} files={files} fileRef={fileRef} onFiles={(names:string[])=>setFiles(c=>[...c,...names])}/>} {view==="profile"&&<Profile t={t} editing={editing} setEditing={setEditing} setView={setView} lang={lang} submitted={intakeSubmitted}/>} {view==="job"&&<JobDetail t={t} job={jobs[selectedJob]} interested={interested} setInterested={setInterested} saved={savedJobs.includes(selectedJob)} toggleSaved={()=>setSavedJobs(s=>s.includes(selectedJob)?s.filter(x=>x!==selectedJob):[...s,selectedJob])}/>} {view==="intake"&&<Intake lang={lang} step={intakeStep} setStep={setIntakeStep} answers={intakeAnswers} setAnswers={setIntakeAnswers} documents={intakeDocuments} setDocuments={setIntakeDocuments} consent={intakeConsent} setConsent={setIntakeConsent} submitted={intakeSubmitted} onSubmit={()=>setIntakeSubmitted(true)} onDone={()=>setView("home")}/>} {view==="jobPreferences"&&<JobPreferences lang={lang}/>} {view==="settings"&&<SettingsPage lang={lang} setLang={setLang}/>} {view==="help"&&<HelpPage lang={lang}/>}</div>{!focused&&<BottomNav t={t} view={view} setView={setView}/>}</div></main>;
}

function Brand({compact=false}:{compact?:boolean}){return <div className={`brand ${compact?"compact":""}`}><img className="brand-logo" src="/medibridge-logo.svg" alt="MediBridge Maghreb"/>{!compact&&<small>Careers in Germany</small>}</div>}
function Dashboard({t,lang,submitted,openJob,setView}:any){const p=processCopy[lang as Language];const score=submitted?100:68;return <><section className="hero-copy"><p className="eyebrow">MEDIBRIDGE CAREERS</p><h1>{t.greeting}</h1><p>{t.subtitle}</p></section><section className={`progress-card ${submitted?"submitted":""}`}><div className="progress-top"><div><span>{submitted?p.status:t.completion}</span><strong>{score}%</strong></div><div className="score-ring">{score}</div></div><Progress value={score} className="profile-progress"/><p>{submitted?p.response:t.completeHint}</p><button className="secondary-button" onClick={()=>setView("intake")}>{submitted?p.viewStatus:t.continue}<ChevronRight size={18}/></button></section><section className="stat-grid"><article><BriefcaseBusiness/><strong>2</strong><span>{t.applications}</span></article><article><Heart/><strong>4</strong><span>{t.saved}</span></article><article className="accent"><Sparkles/><strong>3</strong><span>{t.matches}</span></article></section><SectionHeading title={t.recommended} action={t.seeAll} onClick={()=>setView("jobs")}/><JobCard t={t} job={jobs[0]} onClick={()=>openJob(0)}/><section className="trust-card"><ShieldCheck/><div><strong>{t.privacy}</strong><p>{t.privacyText}</p></div></section></>}
function JobsList({t,savedJobs,setSavedJobs,openJob}:any){return <section><div className="page-heading"><p className="eyebrow">MEDIBRIDGE</p><h1>{t.jobs}</h1><p>{t.anonymous}</p></div><div className="job-list">{jobs.map((job,i)=><div className="job-wrap" key={job.title}><button aria-label="Save job" className={`save-button ${savedJobs.includes(i)?"active":""}`} onClick={()=>setSavedJobs((s:number[])=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}><Heart size={19} fill={savedJobs.includes(i)?"currentColor":"none"}/></button><JobCard t={t} job={job} onClick={()=>openJob(i)}/></div>)}</div></section>}
function JobCard({t,job,onClick}:any){return <button className="job-card" onClick={onClick}><div className={`employer-icon ${job.accent}`}><BriefcaseBusiness/></div><div className="job-card-body"><span className="verified-label"><BadgeCheck size={14}/>{t.verified}</span><h3>{t[job.title]}</h3><div className="job-meta"><span><MapPin size={15}/>{t[job.city]}</span><span><Clock3 size={15}/>{t.fulltime}</span></div><div className="job-footer"><strong>{t[job.salary]}</strong><ChevronRight size={19}/></div></div></button>}
function JobDetail({t,job,interested,setInterested,saved,toggleSaved}:any){return <section className="job-detail"><div className={`detail-hero ${job.accent}`}><div className="employer-icon large"><BriefcaseBusiness/></div><span className="verified-label light"><BadgeCheck size={15}/>{t.verified}</span><h1>{t[job.title]}</h1><p><MapPin size={16}/>{t[job.city]} · {t.fulltime}</p></div><div className="detail-body"><div className="detail-tags"><span>{t[job.salary]}</span><span>{t[job.language]}</span></div><p className="anonymity"><ShieldCheck size={18}/>{t.anonymous}</p><h2>{t.about}</h2><p>{t.aboutText}</p><h2>{t.support}</h2><p>{t.supportText}</p></div><div className="sticky-actions"><button aria-label="Save job" className={`square-button ${saved?"active":""}`} onClick={toggleSaved}><Heart fill={saved?"currentColor":"none"}/></button><button className={`primary-button ${interested?"success":""}`} onClick={()=>setInterested(true)}>{interested?<><Check/>{t.interestSent}</>:<>{t.apply}<ArrowRight size={18}/></>}</button></div></section>}
function Documents({t,files,fileRef,onFiles}:any){const docs=[{name:t.diploma,status:t.uploaded,done:true},{name:t.languageCert,status:t.inReview,done:true},{name:t.passport,status:t.missing,done:false},{name:t.workRef,status:t.missing,done:false}];return <section><div className="page-heading"><p className="eyebrow">MEDIBRIDGE</p><h1>{t.docsTitle}</h1><p>{t.docsSubtitle}</p></div><section className="verification-card"><div className="verification-icon"><BadgeCheck/></div><div><strong>{t.verifiedCandidate}</strong><p>{t.verificationText}</p></div><span>2/4</span></section><div className="document-list">{docs.map(doc=><article key={doc.name}><div className={`doc-icon ${doc.done?"done":""}`}>{doc.done?<FileCheck2/>:<FileText/>}</div><div><strong>{doc.name}</strong><span className={doc.done?"status-done":"status-missing"}>{doc.status}</span></div><ChevronRight size={18}/></article>)}{files.map((file:string)=><article key={file}><div className="doc-icon done"><FileCheck2/></div><div><strong>{file}</strong><span className="status-done">{t.uploaded}</span></div><Check size={18}/></article>)}</div><input ref={fileRef} type="file" hidden multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>onFiles(Array.from(e.target.files??[]).map((f:any)=>f.name))}/><button className="upload-zone" onClick={()=>fileRef.current?.click()}><UploadCloud/><strong>{t.upload}</strong><span>{t.uploadHint}</span></button></section>}
function Profile({t,editing,setEditing,setView,lang,submitted}:any){const fields=[[t.name,"Amira El Mansouri"],[t.country,"Morocco"],[t.role,t.jobTitle],[t.experience,"4 years"],[t.level,"B1"]];const p=processCopy[lang as Language];return <section><div className="profile-header"><ProfileMenu lang={lang} setView={setView}/><div><h1>{t.profileTitle}</h1><p>amira.m@example.com</p></div></div><button className="intake-entry" onClick={()=>setView("intake")}><span>{submitted?<BadgeCheck/>:<ClipboardList/>}<strong>{submitted?p.viewStatus:t.continue}</strong></span><ChevronRight/></button><section className="profile-section"><div className="section-row"><h2>{t.personal}</h2><button className="inline-action" onClick={()=>setEditing(!editing)}>{editing?t.save:t.edit}</button></div>{fields.map(([label,value])=><label className="profile-field" key={label}><span>{label}</span>{editing?<input defaultValue={value}/>:<strong>{value}</strong>}</label>)}</section><section className="cv-card"><div className="cv-icon"><FileText/></div><div><span className="soon-label">{t.comingSoon}</span><h2>{t.cvTitle}</h2><p>{t.cvText}</p></div></section><section className="trust-card"><ShieldCheck/><div><strong>{t.privacy}</strong><p>{t.privacyText}</p></div></section></section>}
function ProfileMenu({lang,setView,compact=false}:any){const m=menuCopy[lang as Language];const items=[{view:"profile",label:m.profile,icon:UserRound},{view:"jobPreferences",label:m.jobPreferences,icon:SlidersHorizontal},{view:"settings",label:m.settings,icon:Settings},{view:"help",label:m.help,icon:HelpCircle}];return <Sheet><SheetTrigger asChild><button className={compact?"mini-avatar":"avatar avatar-button"} aria-label={m.profile}>AM{!compact&&<span><BadgeCheck/></span>}</button></SheetTrigger><SheetContent side={lang==="ar"?"right":"left"} className="profile-menu-sheet" showCloseButton><SheetHeader className="profile-menu-header"><SheetTitle className="sr-only">{m.profile}</SheetTitle><SheetDescription className="sr-only">MediBridge candidate menu</SheetDescription><div className="menu-avatar">AM<span><BadgeCheck/></span></div><div><small>{m.candidate}</small><strong>Amira El Mansouri</strong><p>Pflegefachkraft · B1</p></div></SheetHeader><nav className="profile-menu-nav">{items.map(({view,label,icon:Icon})=><SheetClose asChild key={view}><button onClick={()=>setView(view)}><span><Icon/>{label}</span><ChevronRight/></button></SheetClose>)}</nav><div className="profile-menu-footer"><img src="/medibridge-logo.svg" alt="MediBridge Maghreb"/><p>Careers in Germany</p></div></SheetContent></Sheet>}
function JobPreferences({lang}:any){const m=menuCopy[lang as Language];const values=lang==="ar"?["ممرض/ة مؤهل/ة","شمال الراين-وستفاليا","خلال 3 أشهر","مستشفى أو دار رعاية"]:lang==="de"?["Pflegefachkraft","Nordrhein-Westfalen","Innerhalb von 3 Monaten","Krankenhaus oder Pflegeheim"]:["Registered nurse","North Rhine-Westphalia","Within 3 months","Hospital or care home"];const fields=[[m.desiredRole,values[0]],[m.preferredRegion,values[1]],[m.startDate,values[2]],[m.workplace,values[3]]];return <section className="subpage"><div className="subpage-icon"><SlidersHorizontal/></div><h1>{m.preferencesTitle}</h1><p>{m.preferencesText}</p><div className="preference-list">{fields.map(([label,value])=><label key={label}><span>{label}</span><input defaultValue={value}/></label>)}</div><button className="primary-button"><Check/>{m.save}</button></section>}
function SettingsPage({lang,setLang}:any){const m=menuCopy[lang as Language];const languageTitle=lang==="de"?"Sprache":lang==="ar"?"اللغة":"Language";return <section className="subpage"><div className="subpage-icon"><Settings/></div><h1>{m.settingsTitle}</h1><p>{m.settingsText}</p><section className="language-settings standalone"><div className="language-setting-title"><Languages/><div><strong>{languageTitle}</strong><span>{lang==="de"?"App-Sprache auswählen":lang==="ar"?"اختر لغة التطبيق":"Choose app language"}</span></div></div><div className="language-options">{[{id:"de",label:"Deutsch"},{id:"en",label:"English"},{id:"ar",label:"العربية"}].map(option=><button key={option.id} className={lang===option.id?"active":""} onClick={()=>setLang(option.id)}>{option.label}{lang===option.id&&<Check size={14}/>}</button>)}</div></section><section className="settings-note"><ShieldCheck/><div><strong>{copy[lang as Language].privacy}</strong><p>{copy[lang as Language].privacyText}</p></div></section></section>}
function HelpPage({lang}:any){const m=menuCopy[lang as Language];const items=[{label:m.faq,icon:MessageCircleQuestion},{label:m.contact,icon:HelpCircle},{label:m.privacy,icon:ShieldCheck}];return <section className="subpage"><div className="subpage-icon"><HelpCircle/></div><h1>{m.helpTitle}</h1><p>{m.helpText}</p><div className="help-list">{items.map(({label,icon:Icon})=><button key={label}><span><Icon/>{label}</span><ChevronRight/></button>)}</div></section>}
function Intake({lang,step,setStep,answers,setAnswers,documents,setDocuments,consent,setConsent,submitted,onSubmit,onDone}:any){
  const c=intakeCopy[lang as Language];const p=processCopy[lang as Language];const questionTotal=c.sections.length;const total=questionTotal+2;const icons=[UserRound,Stethoscope,GraduationCap,BriefcaseBusiness,Globe2,PlaneTakeoff];
  if(submitted)return <section className="intake-success status-page"><div className="success-badge"><BadgeCheck/></div><p className="eyebrow">MEDIBRIDGE CAREERS</p><span className="status-pill"><Clock3 size={14}/>{p.status}</span><h1>{p.submitted}</h1><p>{p.submittedText}</p><div className="reference-card"><span>{p.referenceNo}</span><strong>MB-2026-1048</strong></div><p className="response-note">{p.response}</p><div className="next-steps"><h2>{p.nextSteps}</h2>{[p.next1,p.next2,p.next3].map((item,i)=><div key={item}><i>{i+1}</i><span>{item}</span></div>)}</div><button className="primary-button" onClick={onDone}>{p.dashboard}<ArrowRight size={18}/></button></section>;
  const update=(id:string,value:string)=>setAnswers((current:Record<string,string>)=>({...current,[id]:value}));
  const shell=(title:string,hint:string,Icon:any,body:any)=><section className="intake-page"><div className="intake-top"><div><p className="eyebrow">{c.step} {step+1} {c.of} {total}</p><h1>{c.title}</h1><p>{c.intro}</p></div><div className="intake-icon"><Icon/></div></div><Progress value={((step+1)/total)*100} className="intake-progress"/><div className="intake-section-heading"><h2>{title}</h2><p>{hint}</p></div>{body}<p className="intake-privacy"><ShieldCheck size={15}/>{copy[lang as Language].privacyText}</p></section>;
  if(step<questionTotal){const section=c.sections[step];const Icon=icons[step];const complete=section.questions.every((q:any)=>(answers[q.id]??"").trim().length>0);return shell(section.title,section.hint,Icon,<form className="intake-form" onSubmit={e=>{e.preventDefault();if(complete)setStep(step+1)}}>{section.questions.map((q:any)=><div className="question-field" key={q.id}><label>{q.label}<span>*</span></label>{q.type==="choice"?<div className="choice-grid">{q.options.map((option:string)=><button type="button" key={option} className={answers[q.id]===option?"selected":""} onClick={()=>update(q.id,option)}><i>{answers[q.id]===option&&<Check size={13}/>}</i>{option}</button>)}</div>:q.type==="textarea"?<textarea rows={4} value={answers[q.id]??""} placeholder={q.placeholder} onChange={e=>update(q.id,e.target.value)}/>:<input type={q.type} value={answers[q.id]??""} placeholder={q.placeholder} onChange={e=>update(q.id,e.target.value)}/>}</div>)}<div className="intake-actions">{step>0&&<button type="button" className="back-button" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>{c.back}</button>}<button type="submit" className="primary-button" disabled={!complete}>{c.next}<ArrowRight size={18}/></button></div></form>)}
  if(step===questionTotal){const docTypes=[{id:"passport",label:p.passport,required:true},{id:"qualification",label:p.qualification,required:true},{id:"language",label:p.language,required:false},{id:"reference",label:p.reference,required:false}];const complete=!!documents.passport&&!!documents.qualification;return shell(p.documents,p.documentsHint,UploadCloud,<div className="intake-form"><div className="intake-document-grid">{docTypes.map(doc=><label className={`intake-document ${documents[doc.id]?"done":""}`} key={doc.id}><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const name=e.target.files?.[0]?.name;if(name)setDocuments((current:Record<string,string>)=>({...current,[doc.id]:name}))}}/><div className="doc-icon">{documents[doc.id]?<FileCheck2/>:<FileText/>}</div><div><strong>{doc.label}</strong><span>{documents[doc.id]?documents[doc.id]:doc.required?p.required:p.optional}</span></div><b>{documents[doc.id]?p.uploaded:p.choose}</b></label>)}</div><div className="intake-actions"><button type="button" className="back-button" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>{c.back}</button><button type="button" className="primary-button" disabled={!complete} onClick={()=>setStep(step+1)}>{c.next}<ArrowRight size={18}/></button></div></div>)}
  const answeredSections=c.sections.map((section:any,index:number)=>({title:section.title,index,items:section.questions.map((q:any)=>({label:q.label,value:answers[q.id]}))}));return shell(p.review,p.reviewHint,ClipboardList,<div className="review-wrap"><div className="review-groups">{answeredSections.map(group=><section key={group.title}><header><strong>{group.title}</strong><button onClick={()=>setStep(group.index)}>{p.edit}</button></header>{group.items.map((item:any)=><div key={item.label}><span>{item.label}</span><b>{item.value}</b></div>)}</section>)}</div><section className="review-documents"><header><strong>{p.files}</strong><button onClick={()=>setStep(questionTotal)}>{p.edit}</button></header>{Object.entries(documents).map(([id,name])=><div key={id}><FileCheck2/><span>{name as string}</span></div>)}</section><label className="consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{p.consent}</span></label><div className="intake-actions"><button type="button" className="back-button" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>{c.back}</button><button type="button" className="primary-button" disabled={!consent} onClick={onSubmit}>{p.submit}<Check size={18}/></button></div></div>)}
function SectionHeading({title,action,onClick}:any){return <div className="section-heading"><h2>{title}</h2><button onClick={onClick}>{action}<ChevronRight size={16}/></button></div>}
function BottomNav({t,view,setView}:any){const items=[{id:"home",icon:Home,label:t.home},{id:"jobs",icon:BriefcaseBusiness,label:t.jobs},{id:"documents",icon:FileText,label:t.documents},{id:"profile",icon:UserRound,label:t.profile}];return <nav className="bottom-nav" aria-label="Primary">{items.map(({id,icon:Icon,label})=><button className={view===id?"active":""} key={id} onClick={()=>setView(id)}><Icon size={21}/><span>{label}</span>{view===id&&<i/>}</button>)}</nav>}
