import { supabase, type CandidateDocument, type CandidateStatus } from "./supabase";

export type BackofficeCandidate={id:string;full_name:string|null;email:string|null;phone:string|null;nationality:string|null;residence:string|null;preferred_language:"en"|"de"|"ar";status:CandidateStatus;reference_number:string|null;submitted_at:string|null;created_at:string;answers:Record<string,string>;documents:CandidateDocument[]};
export type InternalNote={id:string;note:string;created_at:string;author_id:string};
export type EmailLog={id:string;recipient:string;subject:string;body:string;status:string;created_at:string;sent_at:string|null};

export async function signInBackoffice(email:string,password:string){const result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;const membership=await supabase.from("backoffice_users").select("display_name,role").eq("user_id",result.data.user.id).maybeSingle();if(membership.error||!membership.data){await supabase.auth.signOut();throw new Error("NOT_STAFF")}return membership.data}
export async function getBackofficeSession(){const session=await supabase.auth.getSession();if(!session.data.session?.user||session.data.session.user.is_anonymous)return null;const membership=await supabase.from("backoffice_users").select("display_name,role").eq("user_id",session.data.session.user.id).maybeSingle();return membership.data?{user:session.data.session.user,...membership.data}:null}
export async function signOutBackoffice(){await supabase.auth.signOut()}

export async function listBackofficeCandidates():Promise<BackofficeCandidate[]>{const candidates=await supabase.from("candidates").select("id,full_name,email,phone,nationality,residence,preferred_language,status,reference_number,submitted_at,created_at").order("created_at",{ascending:false});if(candidates.error)throw candidates.error;const ids=(candidates.data??[]).map(x=>x.id);if(ids.length===0)return[];const [intakes,documents]=await Promise.all([supabase.from("candidate_intakes").select("candidate_id,answers").in("candidate_id",ids),supabase.from("candidate_documents").select("id,candidate_id,document_type,file_name,storage_path,mime_type,file_size,verification_status,verification_note,created_at,updated_at").in("candidate_id",ids)]);if(intakes.error)throw intakes.error;if(documents.error)throw documents.error;return(candidates.data??[]).map(candidate=>({...candidate,answers:(intakes.data?.find(x=>x.candidate_id===candidate.id)?.answers??{}) as Record<string,string>,documents:(documents.data??[]).filter(x=>x.candidate_id===candidate.id) as CandidateDocument[]})) as BackofficeCandidate[]}
export async function getCandidateActivity(candidateId:string){const [notes,emails,history]=await Promise.all([supabase.from("candidate_internal_notes").select("id,note,created_at,author_id").eq("candidate_id",candidateId).order("created_at",{ascending:false}),supabase.from("candidate_emails").select("id,recipient,subject,body,status,created_at,sent_at").eq("candidate_id",candidateId).order("created_at",{ascending:false}),supabase.from("candidate_status_history").select("id,previous_status,new_status,note,created_at").eq("candidate_id",candidateId).order("created_at",{ascending:false})]);for(const result of [notes,emails,history])if(result.error)throw result.error;return{notes:(notes.data??[]) as InternalNote[],emails:(emails.data??[]) as EmailLog[],history:history.data??[]}}
export async function addInternalNote(candidateId:string,note:string){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error("UNAUTHENTICATED");const result=await supabase.from("candidate_internal_notes").insert({candidate_id:candidateId,author_id:user.id,note}).select("id,note,created_at,author_id").single();if(result.error)throw result.error;return result.data as InternalNote}
export async function updateCandidateStatus(candidateId:string,previousStatus:CandidateStatus,newStatus:CandidateStatus,note:string){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error("UNAUTHENTICATED");const updated=await supabase.from("candidates").update({status:newStatus,updated_at:new Date().toISOString()}).eq("id",candidateId);if(updated.error)throw updated.error;const history=await supabase.from("candidate_status_history").insert({candidate_id:candidateId,changed_by:user.id,previous_status:previousStatus,new_status:newStatus,note:note||null});if(history.error)throw history.error}
export async function reviewCandidateDocument(documentId:string,status:"pending"|"verified"|"rejected",note:string){const result=await supabase.from("candidate_documents").update({verification_status:status,verification_note:note||null,updated_at:new Date().toISOString()}).eq("id",documentId);if(result.error)throw result.error}
export async function prepareCandidateEmail(candidateId:string,recipient:string,subject:string,body:string){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error("UNAUTHENTICATED");const result=await supabase.from("candidate_emails").insert({candidate_id:candidateId,created_by:user.id,recipient,subject,body,status:"prepared"}).select("id,recipient,subject,body,status,created_at,sent_at").single();if(result.error)throw result.error;window.location.href=`mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;return result.data as EmailLog}
