import {supabase} from "./supabase";
export type Job={id:string;title:string;region:string;employment_type:string;salary_text:string|null;german_level:string|null;description:string;support_text:string|null;employer_reference?:string|null;status:"draft"|"published"|"paused"|"closed";published_at:string|null;created_at:string};
export type JobInterest={id:string;job_id:string;status:string;created_at:string};
export async function listPublishedJobs(){const r=await supabase.from("jobs").select("id,title,region,employment_type,salary_text,german_level,description,support_text,status,published_at,created_at").eq("status","published").order("published_at",{ascending:false});if(r.error)throw r.error;return(r.data??[]) as Job[]}
export async function listMyInterests(){const u=(await supabase.auth.getUser()).data.user;if(!u)return[];const r=await supabase.from("candidate_job_interests").select("id,job_id,status,created_at").eq("candidate_id",u.id);if(r.error)throw r.error;return(r.data??[]) as JobInterest[]}
export async function expressJobInterest(jobId:string){const u=(await supabase.auth.getUser()).data.user;if(!u)throw new Error("PROFILE_REQUIRED");const r=await supabase.from("candidate_job_interests").upsert({candidate_id:u.id,job_id:jobId,status:"expressed",updated_at:new Date().toISOString()},{onConflict:"candidate_id,job_id"}).select("id,job_id,status,created_at").single();if(r.error)throw r.error;return r.data as JobInterest}
export async function listBackofficeJobs(){const r=await supabase.from("jobs").select("*").order("created_at",{ascending:false});if(r.error)throw r.error;return(r.data??[]) as Job[]}
export async function saveBackofficeJob(job:Partial<Job>){const u=(await supabase.auth.getUser()).data.user;if(!u)throw new Error("UNAUTHENTICATED");const payload={...job,created_by:u.id,updated_at:new Date().toISOString(),published_at:job.status==="published"?(job.published_at||new Date().toISOString()):job.published_at||null};const r=job.id?await supabase.from("jobs").update(payload).eq("id",job.id).select("*").single():await supabase.from("jobs").insert(payload).select("*").single();if(r.error)throw r.error;return r.data as Job}
export async function createPrivacyRequest(type:"access"|"correction"|"deletion"|"withdraw_consent"){const u=(await supabase.auth.getUser()).data.user;if(!u)throw new Error("PROFILE_REQUIRED");const r=await supabase.from("data_subject_requests").insert({candidate_id:u.id,request_type:type});if(r.error)throw r.error}
export async function submitPilotFeedback(rating:number,message:string,context:string){const u=(await supabase.auth.getUser()).data.user;const r=await supabase.from("pilot_feedback").insert({candidate_id:u?.id||null,rating,message,context});if(r.error)throw r.error}
